[tool.poetry]
name = "fuelpricesgr"
version = "0.1.0"
description = ""
authors = ["Kostas Kokkoros <mavroprovato@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
argon2-cffi = "^23.1.0"
beautifulsoup4 = "^4.11.2"
boto3 = "^1.26.69"
fastapi = "^0.109.0"
gunicorn = "^21.2.0"
httpx = "^0.26.0"
itsdangerous = "^2.1.2"
pypdf = "^4.0.0"
python-dotenv = "^1.0.0"
requests = "^2.28.2"
redis = "^5.0.1"
sqladmin = "^0.16.0"
SQLAlchemy = "^2.0.3"
uvicorn = "^0.27.0"

[tool.poetry.dev-dependencies]
coverage = "^7.1.0"
patchwork = "^1.0.1"
pylint = "^3.0.1"
pytest = "^7.2.1"
safety = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
