[tool.poetry]
name = "fuelpricesgr"
version = "0.1.0"
description = ""
authors = ["Kostas Kokkoros <mavroprovato@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
argon2-cffi = "^23.1.0"
boto3 = "^1.34.0"
cachelib = "^0.13.0"
environs = "^11.0.0"
fastapi = "^0.111.0"
gunicorn = "^22.0.0"
httpx = "^0.27.0"
itsdangerous = "^2.1.2"
pypdf = "^4.0.0"
requests = "^2.28.2"
psycopg2 = "^2.9.9"
redis = "^5.0.1"
sqladmin = "^0.18.0"
SQLAlchemy = "^2.0.3"
uvicorn = "^0.30.0"
pymongo = "^4.8.0"

[tool.poetry.dev-dependencies]
coverage = "^7.1.0"
patchwork = "^1.0.1"
pylint = "^3.0.1"
pytest = "^8.2.0"
safety = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
